### ISSUE TITLE
Firm Synthesis Model: testing by CMAP

### ISSUE THREAD

**Issue by ColSmith76** [CMAP-REPOS/cmap_freight_model#11]
Placeholder for issues with run on CMAP end.

**Comment by ColSmith76** [comment]
check for consistency between file presence and  locations in modelDevelopment branch and code read locations:
•	data_emp_control_mz.csv
•	data_emp_control_2017.csv

**Comment by tinleycraig** [comment]
@ColSmith76 I got the following error testing firm synthesis: 
Running the base scenario for 2019 
Starting Firm Synthesis Step 
Processing Firm Synthesis Inputs 
Error in eval(jsub, SDenv, parent.frame()) : 
  object 'EmpCatName' not found
Calls: source ... firm_sim_process_inputs -> unique -> [ -> [.data.table -> eval -> eval
In addition: There were 18 warnings (use warnings() to see them)
Execution halted

**Comment by ColSmith76** [comment]
@tinleycraig ok I'll take a look at this

**Comment by ColSmith76** [comment]
@tinleycraig it is a git large file problem, some of the data files in the release package have been replaced with placeholder files including the one that define the employment categories. I'll fix the git lfs settings and recreate the release.

**Comment by ColSmith76** [comment]
@tinleycraig I adjusted the lfs settings in the repo and recreated the release, https://github.com/CMAP-REPOS/cmap_freight_model/releases/tag/v0.3.1

**Comment by tinleycraig** [comment]
@ColSmith76 That resolved the issue.

**Comment by ColSmith76** [comment]
Running okay through firm synthesis. Close this issue and use next testing issue for any bugs
